version: '3'
services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"  # NGINXがアクセスできるようにポートを公開

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # ホストのポート80をコンテナのポート80にマッピング
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web  # webサービスが起動してからnginxを起動
